version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./backend/app:/app/app
      - data:/data
    depends_on:
      - postgres
      - redis
  worker:
    build: ./backend
    command: ["celery", "-A", "app.services.celery_app.celery_app", "worker", "-l", "info", "-Q", "celery", "-c", "1"]
    env_file: .env
    volumes:
      - ./backend/app:/app/app
      - data:/data
    depends_on:
      - backend
      - redis
      - postgres
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=legaldoc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
volumes:
  pgdata:
  data:
  minio:
