version: "3.8"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file: ../.env
    volumes:
      - ./app:/app/app
      - ../data:/data
    depends_on:
      - postgres
      - redis
  worker:
    build: .
    command: ["celery", "-A", "app.services.celery_app.celery_app", "worker", "-l", "info"]
    env_file: ../.env
    volumes:
      - ./app:/app/app
      - ../data:/data
    depends_on:
      - api
      - redis
      - postgres
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=legaldoc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  pgdata:
