# fly.toml app configuration file generated for backend-withered-haze-1115 on 2025-09-29T00:28:01-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-withered-haze-1115'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "data"
  destination = "/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.http]
    type     = "http"
    port     = 8000
    interval = "10s"
    timeout  = "2s"
    method   = "get"
    path     = "/health"
